name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3

      - name: Validate code style using "Standard JS"
        run: npm ci

      - name: Generate build output (should not generate changes)
        run: npm run build

      - name: Validate build output is up-to-date
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "❌ Build output is not up-to-date."
            exit 1
          else
            echo "✅ Build output is up-to-date."
          fi
